# Generated by Django 5.2 on 2025-04-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemod',
            old_name='mnane',
            new_name='mname',
        ),
    ]
