# Generated by Django 5.2 on 2025-04-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_age', models.IntegerField()),
                ('e_sal', models.FloatField()),
                ('e_add', models.CharField(max_length=50)),
            ],
        ),
    ]
